---
kind: pipeline
type: docker
name: default

environment:
  BUILD_IMAGE: cache--${DRONE_REPO_NAME}--${DRONE_BRANCH}

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: rebuild-cache
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t . ${BUILD_IMAGE}
    when:
      event:
        - cron
      cron:
        - rebuild-cache-${DRONE_BRANCH}

  - name: build-vellvm
    image: ${BUILD_IMAGE}
    pull: never
    commands:
      - opam exec -- make -j 1 vellvm

  - name: compile-helix
    image: ${BUILD_IMAGE}
    pull: never
    commands:
      - opam exec -- make

  - name: test-helix
    image: ${BUILD_IMAGE}
    pull: never
    commands:
      - opam exec -- make test

# - name: notify-slack
#   image: plugins/slack
#   settings:
#     webhook:
#       from_secret: slack_webhook
#     channel: bitbucket-activity
#     when:
#       status:
#         - failure
#         - success

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
