---
kind: pipeline
type: docker
name: default

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: test-variables
    image: docker
    commands:
      - echo {{ .repo.name }}
      - echo {{ .build.branch }}

  - name: rebuild-cache
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t cache-{{ .repo.name }}-{{ .build.branch }} .
    when:
      event:
        - cron
      cron:
        - rebuild-cache-{{ .build.branch }}

  - name: build-vellvm
    image: cache-{{ .repo.name }}-{{ .build.branch }}
    pull: never
    commands:
      - opam exec -- make -j 1 vellvm

  # - name: compile-helix
  #   image: cache-{{ .repo.name }}-{{ .build.branch }}
  #   pull: never
  #   commands:
  #     - opam exec -- make

  # - name: test-helix
  #   image: cache-{{ .repo.name }}-{{ .build.branch }}
  #   pull: never
  #   commands:
  #     - opam exec -- make test

  # - name: notify-slack
  #   image: plugins/slack
  #   settings:
  #     webhook:
  #       from_secret: slack_webhook
  #     channel: bitbucket-activity
  #     when:
  #       status:
  #         - failure
  #         - success

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
