kind: pipeline
type: docker
name: default

environment:
  OPAMROOT: ./.opam

steps:

  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: rebuild-opam-cache
    image: ocaml/opam
    user: root
    commands:
      - opam init -y --bare --disable-sandboxing
      - >
        opam switch create ./
        --yes --deps-only
        --repositories=default,coq-released=https://coq.inria.fr/opam/released
    when:
      event:
        - cron
      cron:
        - opam-rebuilds

  - name: save-opam-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - _opam
    when:
      event:
        - cron
      cron:
        - opam-rebuilds

  - name: restore-opam-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - _opam

  - name: test-cache
    image: ocaml/opam
    commands:
      - opam switch
      - ls _opam

  - name: build-vellvm
    image: ocaml/opam
    commands:
      - eval $(opam env)
      - make -j 1 vellvm

  - name: test-helix
    image: ocaml/opam
    commands:
      - make test

volumes:
  - name: cache
    host:
      path: /tmp/cache
